apiVersion: v1
kind: Pod
metadata:
  name: skip-deployment
  labels:
    app: skip

spec:
  restartPolicy: Never
  volumes:
    - name: skip-static
      emptyDir:
        sizeLimit: 1M
  initContainers:
    - name: skip-static
      image: 585193511743.dkr.ecr.us-west-2.amazonaws.com/scimma/skip-web:test
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: skip-static
          mountPath: /static
          readOnly: false
      command: ["python", "manage.py", "collectstatic", "--no-input"]
    - name: skip-migrate
      image: 585193511743.dkr.ecr.us-west-2.amazonaws.com/scimma/skip-web:test
      imagePullPolicy: IfNotPresent
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: db_name
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: db_port
      command: ["python", "manage.py", "migrate"]
  containers:
    - name: skip-web
      image: 585193511743.dkr.ecr.us-west-2.amazonaws.com/scimma/skip-web:test
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: skip-static
          mountPath: /static
          readOnly: false
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: db_name
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: db_port
    - name: skip-ingest
      image: 585193511743.dkr.ecr.us-west-2.amazonaws.com/scimma/skip-web:test
      imagePullPolicy: IfNotPresent
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: db_name
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: hopdevel-skip-db-info
              key: db_port
      command: ["python", "manage.py", "ingestmessages"]
