version: '3.0'
services:
  migrate:
    image: 585193511743.dkr.ecr.us-west-2.amazonaws.com/scimma/skip-web:latest
    entrypoint: ["python", "manage.py", "migrate"]
    container_name: skip-migrate
  web:
    image: 585193511743.dkr.ecr.us-west-2.amazonaws.com/scimma/skip-web:latest
    entrypoint: ["/usr/local/bin/gunicorn", "skip_base.wsgi:application", "--bind=0.0.0.0:8080"]
    container_name: skip
    ports:
      - "80:8080"
    depends_on:
      - migrate
  ingest:
    image: 585193511743.dkr.ecr.us-west-2.amazonaws.com/scimma/skip-web:latest
    container_name: skip-ingest
    entrypoint: ["python", "manage.py", "ingestmessages"]
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - migrate

volumes:
  shared: