{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "skip.serviceAccountName" . }}
  labels:
{{ include "skip.labels" . | indent 4 }}
{{- end -}}
