name: run-tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt -vvv
        pip install -I flake8
    - name: Style Checks
      run: flake8 skip/* --exclude=*/migrations/* --max-line-length=120

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          sudo apt install -y gdal-bin
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -I flake8
      - name: Run Tests
        run: python manage.py test
